"""Time-domain dataset: loads speech/noise/RIR from HDF5 and mixes them."""

from __future__ import annotations

import bisect
import logging
from dataclasses import dataclass

import h5py
import numpy as np
import torch
from torch.utils.data import Dataset
from torch_audiomentations import Compose

from src.augmentations import (
    get_noise_augmentations,
    get_speech_augmentations,
    get_speech_distortions_td,
)
from src.configs.config import AugmentationConfig
from src.dataloader.dataset_config import DatasetConfig, DatasetEntry, Split
from src.dataloader.hdf5 import Hdf5Dataset
from src.utils.utils import combine_noises, mix_audio_signal

logger = logging.getLogger(__name__)


@dataclass
class Sample:
    """One audio sample returned by :class:`TdDataset`.

    Attributes:
        speech:   Clean target signal, shape ``(channels, samples)``.
        noisy:    Degraded mixture (model input), shape ``(channels, samples)``.
        snr:      Target SNR in dB.
        gain:     Applied gain in dB.
        max_freq: Signal bandwidth in Hz.
        idx:      Dataset index.
    """

    speech: np.ndarray
    noisy: np.ndarray
    snr: int
    gain: int
    max_freq: int
    idx: int


def _apply_aug(pipeline: Compose, audio: np.ndarray, sr: int) -> np.ndarray:
    """Run a torch-audiomentations pipeline on a ``(C, T)`` numpy array."""
    x = torch.from_numpy(audio).unsqueeze(0)  # (1, C, T)
    out = pipeline(x, sample_rate=sr)
    result = out.samples if hasattr(out, "samples") else out
    return result.squeeze(0).numpy()


def _fft_convolve(signal: np.ndarray, kernel: np.ndarray) -> np.ndarray:
    """FFT convolution of ``(C, T)`` signal with a 1-D kernel, trimmed to T."""
    out_len = signal.shape[1]
    n = 1
    while n < out_len + len(kernel) - 1:
        n <<= 1
    K = np.fft.rfft(kernel, n=n)
    channels = [
        np.fft.irfft(np.fft.rfft(signal[c], n=n) * K, n=n)[:out_len]
        for c in range(signal.shape[0])
    ]
    return np.stack(channels).astype(np.float32)


def _lookup(
    datasets: list[Hdf5Dataset], cum: list[int], idx: int
) -> tuple[Hdf5Dataset, int]:
    """Translate a flat index into ``(dataset, key_idx)`` using cumulative sizes."""
    ds_idx = bisect.bisect_right(cum, idx)
    key_idx = idx - (cum[ds_idx - 1] if ds_idx > 0 else 0)
    return datasets[ds_idx], key_idx


class TdDataset(Dataset):
    """PyTorch dataset that mixes speech, noise, and RIR into training pairs.

    Each sample is generated by:

    1. Loading and augmenting a speech clip.
    2. Loading and combining 2–5 noise segments.
    3. Optionally applying room reverberation via a real RIR.
    4. Optionally distorting the speech input (training only).
    5. Mixing at a randomly sampled SNR and gain.

    Args:
        speech_files: HDF5 speech dataset entries.
        noise_files:  HDF5 noise dataset entries.
        rir_files:    HDF5 RIR dataset entries (may be empty).
        aug_config:   Augmentation probabilities.
        split:        ``"train"``, ``"valid"``, or ``"test"``.
        sr:           Sample rate in Hz.
        max_len_s:    Crop clips to at most this many seconds (``None`` = no crop).
        snrs:         Discrete SNR grid in dB.
        gains:        Discrete gain grid in dB.
        n_noises:     ``(min, max)`` number of noise tracks to combine.
        seed:         Base RNG seed — sample ``i`` uses ``seed + i``.
    """

    _DEFAULT_SNRS = [-5, 0, 5, 10, 20, 40]
    _DEFAULT_GAINS = [-6, 0, 6]

    def __init__(
        self,
        speech_files: list[DatasetEntry],
        noise_files: list[DatasetEntry],
        rir_files: list[DatasetEntry],
        aug_config: AugmentationConfig,
        split: Split = "train",
        sr: int = 48_000,
        max_len_s: float | None = None,
        snrs: list[int] | None = None,
        gains: list[int] | None = None,
        n_noises: tuple[int, int] = (2, 5),
        seed: int = 42,
    ) -> None:
        super().__init__()

        self.split = split
        self.sr = sr
        self.max_len_s = max_len_s
        self.snrs = snrs or self._DEFAULT_SNRS
        self.gains = gains or self._DEFAULT_GAINS
        self.n_noises = n_noises
        self.seed = seed
        self.is_train = split == "train"

        self._speech = self._open(speech_files, max_len_s=max_len_s)
        self._noise = self._open(noise_files)
        self._rir = self._open(rir_files)

        # Cumulative effective sizes for O(log n) index → (dataset, key) lookup
        self._speech_cum = self._cumulative(self._speech)
        self._noise_cum = self._cumulative(self._noise)
        self._rir_cum = self._cumulative(self._rir)

        self._speech_aug = get_speech_augmentations(aug_config, sample_rate=sr)
        self._noise_aug = get_noise_augmentations(aug_config, sample_rate=sr)
        self._distortions = (
            get_speech_distortions_td(aug_config, sample_rate=sr)
            if self.is_train
            else None
        )
        for aug in filter(None, [self._speech_aug, self._noise_aug, self._distortions]):
            aug.train()

        logger.info(
            "%s | split=%s | speech=%d | noise=%d | rir=%d",
            self.__class__.__name__,
            split,
            self._speech_cum[-1] if self._speech_cum else 0,
            self._noise_cum[-1] if self._noise_cum else 0,
            self._rir_cum[-1] if self._rir_cum else 0,
        )

    # ------------------------------------------------------------------
    # Dataset protocol
    # ------------------------------------------------------------------

    def __len__(self) -> int:
        return self._speech_cum[-1] if self._speech_cum else 0

    def __getitem__(self, idx: int) -> Sample:
        rng = np.random.default_rng(self.seed + idx)
        snr = int(rng.choice(self.snrs))
        gain = int(rng.choice(self.gains))

        speech = self._load_speech(idx, rng)
        noise = self._load_and_combine_noise(speech.shape, rng)

        speech, noise = self._apply_rir(speech, noise, rng)
        speech_input = (
            _apply_aug(self._distortions, speech, self.sr)
            if self._distortions
            else speech
        )

        _, _, noisy = mix_audio_signal(speech, noise, snr, gain, speech_input)

        ds, _ = _lookup(self._speech, self._speech_cum, idx % self._speech_cum[-1])
        return Sample(
            speech=speech,
            noisy=noisy,
            snr=snr,
            gain=gain,
            max_freq=ds.max_freq,
            idx=idx,
        )

    # ------------------------------------------------------------------
    # Loading helpers
    # ------------------------------------------------------------------

    def _load_speech(self, idx: int, rng: np.random.Generator) -> np.ndarray:
        """Load, loop-extend, crop, and augment one speech clip."""
        ds, key_idx = _lookup(
            self._speech, self._speech_cum, idx % self._speech_cum[-1]
        )
        min_samples = int(self.max_len_s * self.sr * 1.1) if self.max_len_s else 0
        audio = ds.get_at_least(key_idx, min_samples, rng)

        for _ in range(10):
            if self.max_len_s:
                max_s = int(self.max_len_s * self.sr)
                if audio.shape[1] > max_s:
                    start = int(rng.integers(0, audio.shape[1] - max_s + 1))
                    audio = audio[:, start : start + max_s]

            audio = _apply_aug(self._speech_aug, audio, self.sr)

            if audio.max() > 1e-8:
                return audio

            key_idx = int(rng.integers(0, ds.effective_size))
            audio = ds.get_at_least(key_idx, min_samples, rng)

        return audio

    def _load_noise(self, rng: np.random.Generator) -> np.ndarray:
        """Load and augment one randomly chosen noise clip."""
        if not self._noise_cum:
            return np.zeros((1, self.sr), dtype=np.float32)
        flat_idx = int(rng.integers(0, self._noise_cum[-1]))
        ds, key_idx = _lookup(self._noise, self._noise_cum, flat_idx)
        return _apply_aug(self._noise_aug, ds.__getitem__(key_idx, rng=rng), self.sr)

    def _load_and_combine_noise(
        self, speech_shape: tuple[int, ...], rng: np.random.Generator
    ) -> np.ndarray:
        n = int(rng.integers(self.n_noises[0], self.n_noises[1] + 1))
        return combine_noises(
            num_channels=speech_shape[0],
            target_length=speech_shape[1],
            noises=[self._load_noise(rng) for _ in range(n)],
            rng=rng,
        )

    def _apply_rir(
        self,
        speech: np.ndarray,
        noise: np.ndarray,
        rng: np.random.Generator,
    ) -> tuple[np.ndarray, np.ndarray]:
        """Convolve speech and noise with a random RIR (if available).

        Produces two RIR versions for speech:
        - Full RIR → used in the noisy mixture.
        - Suppressed late-tail RIR → blended with dry speech to form the target,
          so the model doesn't need to predict full dereverberation.
        """
        if not self._rir_cum:
            return speech, noise

        flat_idx = int(rng.integers(0, self._rir_cum[-1]))
        ds, key_idx = _lookup(self._rir, self._rir_cum, flat_idx)
        rir = ds.__getitem__(key_idx, rng=rng)[0]  # first channel, shape (T,)
        rir = (rir / (np.sqrt(np.sum(rir**2)) + 1e-10)).astype(np.float32)

        # Suppress late reverb tail: exponential decay after peak + 20 ms
        peak = int(np.argmax(np.abs(rir)))
        cutoff = peak + int(0.020 * self.sr)
        rir_target = rir.copy()
        if cutoff < len(rir_target):
            tail = np.arange(len(rir_target) - cutoff, dtype=np.float32)
            rir_target[cutoff:] *= np.exp(-tail / (0.1 * self.sr))

        noise_rev = _fft_convolve(noise, rir)
        speech_little_rev = _fft_convolve(speech, rir_target)
        drr_f = float(rng.uniform(0.0, 1.0))
        speech_target = (drr_f * speech + (1.0 - drr_f) * speech_little_rev).astype(
            np.float32
        )

        return speech_target, noise_rev

    # ------------------------------------------------------------------
    # Construction helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _open(
        entries: list[DatasetEntry], max_len_s: float | None = None
    ) -> list[Hdf5Dataset]:
        return [
            Hdf5Dataset(
                str(e.path), sampling_factor=e.sampling_factor, max_len_s=max_len_s
            )
            for e in entries
        ]

    @staticmethod
    def _cumulative(datasets: list[Hdf5Dataset]) -> list[int]:
        """Cumulative effective sizes: ``[ds0.size, ds0.size + ds1.size, ...]``."""
        cum, total = [], 0
        for ds in datasets:
            total += ds.effective_size
            cum.append(total)
        return cum

    # ------------------------------------------------------------------
    # Cleanup
    # ------------------------------------------------------------------

    def close(self) -> None:
        for ds in self._speech + self._noise + self._rir:
            ds.close()

    def __del__(self) -> None:
        self.close()

    def __repr__(self) -> str:
        n_speech = self._speech_cum[-1] if self._speech_cum else 0
        n_noise = self._noise_cum[-1] if self._noise_cum else 0
        n_rir = self._rir_cum[-1] if self._rir_cum else 0
        return (
            f"TdDataset(split='{self.split}', speech={n_speech}, "
            f"noise={n_noise}, rir={n_rir})"
        )


class Datasets:
    """Container for train / valid / test :class:`TdDataset` splits.

    Usage::

        cfg = DatasetConfig.from_path("datasets/configs/prototype/dataset.cfg",
                                      ds_dir="datasets/hdf5")
        datasets = Datasets.from_config(cfg, aug_config)
        for sample in DataLoader(datasets.train, batch_size=8):
            ...
    """

    def __init__(self, train: TdDataset, valid: TdDataset, test: TdDataset) -> None:
        self.train = train
        self.valid = valid
        self.test = test

    def get(self, split: Split) -> TdDataset:
        return getattr(self, split)

    @classmethod
    def from_config(
        cls,
        dataset_config: DatasetConfig,
        aug_config: AugmentationConfig,
        sr: int = 48_000,
        max_len_s: float | None = None,
        snrs: list[int] | None = None,
        gains: list[int] | None = None,
        n_noises: tuple[int, int] = (2, 5),
        seed: int = 42,
    ) -> "Datasets":
        """Build all three splits from a :class:`DatasetConfig`.

        HDF5 files are automatically routed into speech / noise / RIR buckets
        by reading the top-level group name from each file.
        """

        def build(split: Split) -> TdDataset:
            speech, noise, rir = _partition(dataset_config.get_split(split))
            return TdDataset(
                speech_files=speech,
                noise_files=noise,
                rir_files=rir,
                aug_config=aug_config,
                split=split,
                sr=sr,
                max_len_s=max_len_s,
                snrs=snrs,
                gains=gains,
                n_noises=n_noises,
                seed=seed,
            )

        return cls(train=build("train"), valid=build("valid"), test=build("test"))

    def close(self) -> None:
        for ds in (self.train, self.valid, self.test):
            ds.close()

    def __repr__(self) -> str:
        return f"Datasets(train={self.train}, valid={self.valid}, test={self.test})"


def _partition(
    entries: list[DatasetEntry],
) -> tuple[list[DatasetEntry], list[DatasetEntry], list[DatasetEntry]]:
    """Split HDF5 entries into (speech, noise, rir) by top-level group name."""
    speech, noise, rir = [], [], []
    for entry in entries:
        try:
            with h5py.File(entry.path, "r") as f:
                ds_type = str(list(f.keys())[0])
        except OSError as exc:
            logger.warning("Skipping %s: %s", entry.path, exc)
            continue

        if ds_type in ("speech", "noisy"):
            speech.append(entry)
        elif ds_type == "noise":
            noise.append(entry)
        elif ds_type == "rir":
            rir.append(entry)
        else:
            logger.warning(
                "Unknown dataset type '%s' in %s — skipping", ds_type, entry.path
            )

    return speech, noise, rir
